apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.name }}"
    role: stress
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: "{{ .Values.name }}"
        role: stress
    spec:
      containers:
      - name: stress-test
        image: "{{ .Values.image }}"
        ports:
        - containerPort: {{ .Values.internalPort }}
          name: metrics-stress
          protocol: TCP
        command: ["guillotina", "-c", "config.json", "stress", "--debug", "--rate", "{{ .Values.request_rate }}", "--time", "{{ .Values.experiment_minutes}}"]
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-config
      restartPolicy: Never
  backoffLimit: 4
