image: ADD_IMAGE_TAG_HERE

resources:
  requests:
    cpu: "100m"
    memory: "800Mi"
  limits:
    memory: "1500Mi"
    cpu: "1"

# Experiment config
request_rate: 20
experiment_minutes: 60

# Memcached config
# memcached_hosts: host1:11211, host2:11211
