image: ADD_IMAGE_TAG_HERE

resources:
  requests:
    cpu: "100m"
    memory: "800Mi"
  limits:
    memory: "1500Mi"
    cpu: "1"

# Experiment config ###########

## Note: tune replicas and request_rate to have traffic streams from
## different jobs/memcached client connections
replicas: 1
request_rate: 20
experiment_minutes: 60

# Memcached config ############
memcached_hosts: localhost:11211
