image: "gcr.io/graceful-earth-112011/memcached-stress:latest"

name: "memcached-stress"
namespace: "default"

resources:
  requests:
    cpu: "100m"
    memory: "800Mi"
  limits:
    memory: "1500Mi"
    cpu: "1"

# Experiment config ###########

## Note: tune replicas and request_rate to have traffic streams from
## different jobs/memcached client connections
replicas: 2
request_rate: 20
experiment_minutes: 60

# Memcached config ############
memcached_hosts: memcached-test-a01.intra.onna.internal:11211, memcached-test-b01.intra.onna.internal:11211
